import 'dart:convert';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:timeago/timeago.dart' as timeago;
import '/flutter_flow/custom_functions.dart';
import '/flutter_flow/lat_lng.dart';
import '/flutter_flow/place.dart';
import '/flutter_flow/uploaded_file.dart';

List<String> getAllChainLevelIds() {
  return [
    "chain1_1",
    "chain1_2",
    "chain1_3",
    "chain1_4",
    "chain1_5",
    "chain1_6",
    "chain1_7",
    "chain1_8",
    "chain1_9",
    "chain1_10",
    "chain2_1",
    "chain2_2",
    "chain2_3",
    "chain2_4",
    "chain2_5",
    "chain2_6",
    "chain2_7",
    "chain2_8",
    "chain2_9",
    "chain2_10",
    "chain3_1",
    "chain3_2",
    "chain3_3",
    "chain3_4",
    "chain3_5",
    "chain3_6",
    "chain3_7",
    "chain3_8",
    "chain3_9",
    "chain3_10",
    "chain4_1",
    "chain4_2",
    "chain4_3",
    "chain4_4",
    "chain4_5",
    "chain4_6",
    "chain4_7",
    "chain4_8",
    "chain4_9",
    "chain4_10",
    "chain5_1",
    "chain5_2",
    "chain5_3",
    "chain5_4",
    "chain5_5",
    "chain5_6",
    "chain5_7",
    "chain5_8",
    "chain5_9",
    "chain5_10",
    "chain6_1",
    "chain6_2",
    "chain6_3",
    "chain6_4",
    "chain6_5",
    "chain6_6",
    "chain6_7",
    "chain6_8",
    "chain6_9",
    "chain6_10",
    "chain7_1",
    "chain7_2",
    "chain7_3",
    "chain7_4",
    "chain7_5",
    "chain7_6",
    "chain7_7",
    "chain7_8",
    "chain7_9",
    "chain7_10",
    "chain8_1",
    "chain8_2",
    "chain8_3",
    "chain8_4",
    "chain8_5",
    "chain8_6",
    "chain8_7",
    "chain8_8",
    "chain8_9",
    "chain8_10",
    "chain9_1",
    "chain9_2",
    "chain9_3",
    "chain9_4",
    "chain9_5",
    "chain9_6",
    "chain9_7",
    "chain9_8",
    "chain9_9",
    "chain9_10",
  ];
}
